[build]
  publish = "."

[functions]
  directory = "netlify/functions/"
  node_bundler = "esbuild"

# Nova secção para a nossa "porta de segurança"
[[edge_functions]]
  # Para qualquer página dentro de /desafio/, execute a nossa função de proteção
  path = "/desafio/*"
  function = "auth-protector"
